source "https://rubygems.org"

ruby "4.0.2"

gem "roda", "~> 3.85"
gem "rack", "~> 3.1"
gem "puma", "~> 6.4"
gem "aws-sdk-sqs", "~> 1.88"
gem "json"

group :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
end
